batch_size: 32                  # batch size
epochs: 100                     # total number of epochs
eval_every_n_epochs: 1          # validation frequency
fine_tune_from: node_masked     # sub directory of pre-trained model in ./ckpt (i.e. node_masked / subgraph_masked)
log_every_n_steps: 50           # print training log frequency
fp16_precision: False           # float precision 16 (i.e. True/False)
init_lr: 0.0005                 # initial learning rate for the prediction head
init_base_lr: 0.0001            # initial learning rate for the base GNN encoder
weight_decay: 1e-6              # weight decay of Adam
gpu: cuda:0                     # training GPU
task_name: Tox21                 # name of fine-tuning benchmark, inlcuding
                                # classifications: BBBP/BACE/ClinTox/Tox21/HIV/SIDER/MUV
                                # regressions: FreeSolv/ESOL/Lipo/qm7/qm8/qm9

model_type: graph_transform                 # GNN backbone (i.e., gin/gcn)
model: 
  num_layer: 5                  # number of graph conv layers
  emb_dim: 300                  # embedding dimension in graph conv layers
  feat_dim: 512                 # output feature dimention
  drop_ratio: 0.3               # dropout ratio
  pool: max                    # readout pooling (i.e., mean/max/add)
  use_3D: True

dataset:
  num_workers: 0                # dataloader number of workers
  valid_size: 0.1               # ratio of validation data
  test_size: 0.1                # ratio of test data
  splitting: tox21           # data splitting (i.e., random/scaffold/tox21)
  use_3D: True